cluster:
  name: katto

opencost:
  enabled: false

metrics:
  node-exporter:
    metricsTuning:
      useIntegrationAllowList: true
  cost:
    enabled: false

  kube-state-metrics:
    metricsTuning:
      includeMetrics:
        - "kube_pod_*"
        - "kube_namespace_created"

externalServices:
  prometheus:
    host: "http://prometheus-server.prometheus.svc.cluster.local"
    writeEndpoint: "/api/v1/write"
    authMode: "none"
  loki:
    host: http://loki-gateway.loki.svc.cluster.local
    authMode: "none"