deployments:
  - path: apps/cert-manager
  - path: apps/alloy
  - path: apps/traefik
  - path: apps/uptime-kuma
  - path: apps/calibre
  - path: apps/dyndns
  - path: apps/vikunja
  - path: apps/gitlab
  - path: apps/grafana
  - path: apps/loki
  - path: apps/prometheus
  - path: apps/clustersecret
  - path: apps/sharkey
  - path: apps/terraria

vars:
  - file: secrets.yaml