deployments:
  - path: apps/cert-manager
  - path: apps/alloy
  - path: apps/traefik
  - path: apps/uptime-kuma
  - path: apps/calibre
  - path: apps/dyndns
  - path: apps/vikunja
  - path: apps/gitlab
  - path: apps/grafana
  - path: apps/loki
  - path: apps/prometheus
  - path: apps/clustersecret
  - path: apps/sharkey
  - path: apps/terraria
  - path: apps/kluctl
  - git:
      url: https://github.com/kluctl/kluctl.git
      subDir: install/controller
      ref:
        tag: v2.25.1
    vars:
      - values:
          args:
            controller_envs:
              # Allow the kluctl operator to decrypt our secrets using the age key we gave it
              # The key is encrypted with our sops key, meaning the first deploy must be manual, but it must be manual anyways
              # to install the operator so this is ok
              - name: SOPS_AGE_KEY
                valueFrom:
                  secretKeyRef:
                    name: kluctl-age-key
                    key: key

vars:
  - file: secrets.yaml