global:
  ssh: 'ssh.amy.mov'
  hosts:
    domain: amy.mov
    https: true
    gitlab:
      https: true
    registry:
      https: true
    kas:
      https: true
    pages:
      https: true
  pages:
    enabled: true
    host: pages.amy.mov
    namespaceInPath: true
  email:
    reply_to: 'do-not-reply@amy.mov'
    from: 'do-not-reply@amy.mov'
  smtp:
    enabled: true
    address: 'monday.mxrouting.net'
    user_name: 'do-not-reply@amy.mov'
    port: 465
    tls: true
    password:
      secret: gitlab-smtp-secret
  ingress:
    configureCertmanager: false
    enabled: true
    tls:
      enabled: true
      secretName: letsencrypt
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    class: traefik
    provider: traefik

nginx-ingress:
  enabled: false

gitlab-runner:
  gitlabUrl: https://amy.mov
  runners:
    secret: gitlab-runner-secret
    config: |
      [[runners]]
        name = "Shared Runner"
        url = "https://gitlab.amy.mov"
        id = 15
        executor = "docker"
        clone_url = "https://gitlab.amy.mov"
        [runners.kubernetes]
        image = "ubuntu:22.04"
        [runners.cache]
          Type = "s3"
          Path = "gitlab-runner"
          Shared = true
          [runners.cache.s3]
            ServerAddress = "minio.amy.mov"
            BucketName = "runner-cache"
            Insecure = false
  rbac:
    create: true