apiVersion: apps/v1
kind: Deployment
metadata:
  name: satisfactory
  namespace: satisfactory
spec:
  selector:
    matchLabels:
      app: satisfactory
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      containers:
      - name: satisfactory
        image: wolveix/satisfactory-server:latest
        env:
          - name: "PGID"
            value: "1000"
          - name: "PUID"
            value: "1000"
          - name: "ROOTLESS"
            value: "false"
          - name: "STEAMBETA"
            value: "false"
          - name: "MAXPLAYERS"
            value: "4"
          # - name: "DEBUG"
          #   value: "true"
        resources:
          limits:
            memory: "8G"
            cpu: "3000m"
          requests:
            memory: "1G"
            cpu: "500m"
        volumeMounts:
          - mountPath: /config
            name: satisfactory-data
        ports:
        - containerPort: 7777
          protocol: UDP
        - containerPort: 7777
          protocol: TCP
      volumes:
        - name: satisfactory-data
          persistentVolumeClaim:
            claimName: satisfactory-data
---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory-svc
  namespace: satisfactory
spec:
  selector:
    app: satisfactory
  ports:
  - port: 7777
    protocol: TCP
    name: 'satisfactory'
    targetPort: 7777
  - port: 6666
    protocol: UDP
    name: 'satisfactory-udp'
    targetPort: 7777
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-data
  namespace: satisfactory
  labels:
    app: satisfactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '10Gi'