apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: grafana
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`grafana.amy.mov`)
    kind: Rule
    services:
    - name: grafana
      port: 80
  tls:
    certResolver: letsencrypt