apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homarr-ingress
  namespace: homarr
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`dash.amy.mov`)
    kind: Rule
    services:
    - name: homarr
      port: 7575
  tls:
    secretName: cf-origin