apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer-ingress
  namespace: portainer
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`portainer.amy.mov`) 
    kind: Rule 
    services:
    - name: portainer
      port: 9000
  tls:
    secretName: cf-origin