apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-kuma-ingress
  namespace: uptime-kuma
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`amy.mov`)
    kind: Rule
    services:
    - name: uptime-kuma-svc
      port: 3001
  tls:
    secretName: cf-origin