kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  namespace: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v3.1
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          args:
            - --accesslog

            - --providers.kubernetesingress
            - --providers.kubernetesCRD
            - --providers.kubernetesCRD.allowCrossNamespace=true

            - --log.level=DEBUG
            - --log.format=json

            - --entryPoints.web.address=:80
            - --entryPoints.minecraft.address=:25565
            - --entryPoints.web.http.redirections.entryPoint.to=websecure
            - --entryPoints.websecure.address=:443
            - --entryPoints.gitlab-shell.address=:22
            - --entryPoints.factorio.address=:30000
            - --entryPoints.satisfactory.address=:7777/tcp
            - --entryPoints.satisfactory-udp.address=:7777/udp
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: gitlab-shell
              containerPort: 22
            - name: minecraft
              containerPort: 25565
            - name: satisfactory
              protocol: TCP
              containerPort: 7777
            - name: factorio
              protocol: TCP
              containerPort: 30000
            - name: satis-udp
              protocol: UDP
              containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: websecure
      port: 443
    - protocol: TCP
      name: gitlab-shell
      port: 22
    - protocol: TCP
      name: minecraft
      port: 25565
    - protocol: TCP
      name: satisfactory
      port: 7777
    - protocol: TCP
      name: factorio
      port: 30000
    - protocol: UDP
      name: satisfactory-udp
      port: 7777
  selector:
    app: traefik
