apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vikunja-ingress
  namespace: vikunja
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`vikunja.amy.mov`) 
    kind: Rule 
    services:
    - name: vikunja-frontend
      port: 80
  - match: Host(`vikunja.amy.mov`) && PathPrefix(`/api`)
    kind: Rule
    services:
    - name: vikunja-api
      port: 3456
  tls:
    secretName: cf-origin