{{- if and (not .Values.bridges.hookshot.existingConfigMap) (not .Values.bridges.hookshot.existingSecret.config) .Values.bridges.hookshot.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix.hookshot.configmap" . }}
  labels:
  {{ include "matrix.labels" . | nindent 4}}
data:
  config.yml: |-
    {{ include "hookshot_config.yaml" . | nindent 4 }}
{{- end }}
