{{- if and .Values.bridges.hookshot.enabled (not .Values.bridges.hookshot.existingSecret.passkey) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix.hookshot.passkeySecret" . }}
  labels:
  {{ include "matrix.labels" . | nindent 4}}
data:
  {{ if .Values.bridges.hookshot.passkey }}
  passkey.pem: {{ .Values.bridges.hookshot.passkey | trim | b64enc | quote }}
  {{- else -}}
  passkey.pem: {{ genPrivateKey "rsa" | trim | b64enc | quote }}
  {{- end }}
{{- end }}
