apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab
type: Opaque
data:
  # Need to leave as an empty string for compatibility reasons
  runner-registration-token: "" 
  runner-token: "{{ secrets.gitlab.runnerToken }}"