{{/*
if postgresql.global.postgresql.auth.existingSecret is not passed in, then we create a
secret to store the credentials without it being in a configmap in plaintext.
*/}}
{{- if and .Values.postgresql.enabled (not .Values.postgresql.global.postgresql.auth.existingSecret)}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matrix-sliding-sync.fullname" . }}-db-secret
  labels:
    app.kubernetes.io/name: {{ include "matrix-sliding-sync.name" . }}
    helm.sh/chart: {{ include "matrix-sliding-sync.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  hostname: {{ include "matrix-sliding-sync.postgresql.hostname" . | b64enc | quote }}
  database: {{ .Values.postgresql.global.postgresql.auth.database | b64enc | quote }}
  username: {{ .Values.postgresql.global.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.global.postgresql.auth.password | b64enc | quote }}
{{- end }}
