apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-vanilla
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: mc-vanilla
  template:
    metadata:
      labels:
        app: mc-vanilla
    spec:
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data
      containers:
      - image: itzg/minecraft-server
        name: mc-vanilla
        env:
        - name: EULA
          value: "true"
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 25565
        readinessProbe:
          exec:
            command: [ "/usr/local/bin/mc-monitor", "status", "--host", "localhost" ]
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 20
        livenessProbe:
          exec:
            command: ["/usr/local/bin/mc-monitor", "status", "--host", "localhost"]
          initialDelaySeconds: 120
          periodSeconds: 60
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: minecraft
spec:
  resources:
    requests:
      storage: '15Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: mc-vanilla-svc
  namespace: minecraft
spec:
  type: LoadBalancer
  ports:
  - port: 25565
  selector:
    app: mc-vanilla