apiVersion: v2
appVersion: v1.115.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.1.4
- condition: coturn.enabled
  name: coturn
  repository: https://small-hack.github.io/coturn-chart
  version: 6.2.1
- alias: syncv3
  condition: syncv3.enabled
  name: matrix-sliding-sync
  repository: https://small-hack.github.io/matrix-sliding-sync-chart
  version: 0.5.1
- alias: mas
  condition: mas.enabled
  name: matrix-authentication-service
  repository: https://small-hack.github.io/matrix-authentication-service-chart
  version: 0.8.1
description: A Helm chart to deploy a Matrix homeserver stack on Kubernetes
home: https://github.com/small-hack/matrix-chart
icon: https://dacruz21.github.io/helm-charts/icons/matrix.svg
maintainers:
- name: jessebot
  url: https://github.com/jessebot
name: matrix
sources:
- https://github.com/small-hack/matrix-chart
type: application
version: 13.3.1
