kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dash-role
  namespace: dash
rules:
  - apiGroups:
      - ""
      - "batch"
      - "apps"
      - "networking.k8s.io"
    resources:
      - '*'
    verbs:
      - '*'