kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dash-role-binding
  namespace: dash
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dash-role
subjects:
  - kind: ServiceAccount
    name: dash-account
    namespace: dash
