apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dash-ingress
  namespace: dash
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`dash.amy.mov`)
    kind: Rule
    services:
    - name: dash-kong-proxy
      port: 80
  tls:
    secretName: cf-origin