apiVersion: v1
kind: ServiceAccount
metadata:
  name: dash-account
  namespace: dash
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dash-role
  namespace: dash
rules:
  - apiGroups:
      - ""
      - "batch"
      - "apps"
      - "networking.k8s.io"
    resources:
      - '*'
    verbs:
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dash-role-binding
  namespace: dash
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dash-role
subjects:
  - kind: ServiceAccount
    name: dash-account
    namespace: dash

