apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria
  namespace: terraria
spec:
  selector:
    matchLabels:
      app: terraria
  template:
    metadata:
      labels:
        app: terraria
    spec:
      volumes:
        - name: terraria-data
          persistentVolumeClaim:
            claimName: terraria-pvc
      containers:
      - name: terraria
        image: hexlo/terraria-server-docker
        env:
          - name: world
            value: '/root/.local/share/Terraria/Worlds/catppuccin.wld'
          - name: autocreate
            value: '2'
          - name: worldname
            value: 'catppuccin'
          - name: difficulty
            value: '1'
          - name: maxplayers
            value: '8'
          - name: port
            value: '7777'
          - name: password
            value: 'cat'
        resources:
          limits:
            cpu: '500m'
            memory: '1Gi'
        ports:
        - containerPort: 7777
        volumeMounts:
        - mountPath: "/root/.local/share/Terraria/Worlds"
          name: terraria-data
---
apiVersion: v1
kind: Service
metadata:
  name: terraria-svc
  namespace: terraria
spec:
  selector:
    app: terraria
  ports:
  - port: 7777
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraria-pvc
spec:
  resources:
    requests:
      storage: '15Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
