---
kind: pipeline
type: docker
name: build

trigger:
  branch:
    include:
      - main
  event:
    include:
      - push
      - pull_request

steps:
  - name: build
    image: alpine/helm
    pull: always
    commands:
      - helm dependency update
      - helm package .

---
kind: pipeline
type: docker
name: release

depends_on:
  - build

trigger:
  event:
    - tag

steps:
  - name: build
    image: alpine/helm
    pull: always
    environment:
      HELM_PASSWORD:
        from_secret: helm_password
    commands:
      - helm dependency update
      - helm package .
      - echo $${HELM_PASSWORD} | helm registry login -u frederick --password-stdin kolaente.dev/vikunja
      - helm push vikunja-*.tgz oci://kolaente.dev/vikunja   
---
kind: signature
hmac: 0f07e164aa169160b10e2813884d8de17a207ac10d4b3f03026e0a9a175acb83

...
