apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharkey
  namespace: sharkey
spec:
  selector:
    matchLabels:
      app: sharkey
  template:
    metadata:
      labels:
        app: sharkey
    spec:
      volumes:
        - name: sharkey-data
          persistentVolumeClaim:
            claimName: sharkey-volume-claim
        - name: sharkey-config
          configMap:
            name: sharkey-config
      containers:
      - name: sharkey
        image: registry.activitypub.software/transfem-org/sharkey:latest
        ports:
          - containerPort: 3000
        resources:
          limits:
            cpu: '3000m'
            memory: '2Gi'
          requests:
            cpu: '500m'
            memory: '500Mi'
        env:
          - name: MISSKEY_CONFIG_YML
            value: '/sharkey/.config/default.yaml'
          - name: MK_VERBOSE
            value: 'true'
        volumeMounts:
        - mountPath: "/sharkey/.config"
          name: sharkey-config
        - mountPath: "/sharkey/files"
          name: sharkey-data
---
apiVersion: v1
kind: Service
metadata:
  name: sharkey-svc
  namespace: sharkey
spec:
  selector:
    app: sharkey
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharkey-volume-claim
  namespace: sharkey
  labels:
    app: sharkey
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '100Gi'