
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-volume-claim
  namespace: sharkey
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '10Gi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: sharkey
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: 'redis:7'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-data
          resources:
            limits: 
              cpu: '500m'
              memory: '512Mi'
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: sharkey
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
