{{- if and (not .Values.bridges.alertmanager.existingSecret.registration) .Values.bridges.alertmanager.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix.alertmanager.registrationSecret" . }}
  labels:
  {{ include "matrix.labels" . | nindent 4}}
stringData:
  registration.yaml: |
    id: {{ .Values.bridges.alertmanager.registration.id }}
    {{ if .Values.bridges.alertmanager.registration.url }}
    url: {{ .Values.bridges.alertmanager.registration.url }}
    {{- else -}}
    url: http://{{ include "matrix.fullname" .}}-bridge-alertmanager:{{ .Values.bridges.alertmanager.config.app_port }}
    {{- end }}
    rate_limited: false
    sender_localpart: {{ .Values.bridges.alertmanager.registration.sender_localpart }}
    as_token: "{{ include "matrix.alertmanager.as_token" . }}"
    hs_token: "{{ include "matrix.alertmanager.hs_token" . }}"
    namespaces:
      users:
        - exclusive: true
          regex: "^@alertmanager.*:{{ .Values.matrix.serverName }}$"
        - exclusive: true
          regex: "^@{{ .Values.bridges.alertmanager.config.matrix_user }}:{{ .Values.matrix.serverName }}$"
    {{- if .Values.bridges.alertmanager.encryption }}
    de.sorunome.msc2409.push_ephemeral: true
    push_ephemeral: true
    {{- end }}
{{- end }}
