apiVersion: apps/v1
kind: Deployment
metadata:
  name: forjeo
  namespace: forjeo
spec:
  selector:
    matchLabels:
      app: forjeo
  template:
    metadata:
      labels:
        app: forjeo
    spec:
      volumes:
        - name: forjeo-data
          persistentVolumeClaim:
            claimName: forjeo-data
      containers:
      - name: forjeo
        image: codeberg.org/forgejo/forgejo:7.0.3
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
          - name: EXTERNAL_URL
            value: https://forjeo.amy.mov
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: "/data"
          name: forjeo-data
---
apiVersion: v1
kind: Service
metadata:
  name: forjeo-svc
  namespace: forjeo
spec:
  selector:
    app: forjeo
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forjeo-data
  namespace: forjeo
spec:
  resources:
    requests:
      storage: '5Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce