{{- if not .Values.mas.matrix.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matrix-authentication-service.fullname" . }}-matrix-secret
data:
  secret: {{ .Values.mas.matrix.secret | b64enc | quote }}
{{- end }}
