{{- if and (not .Values.bridges.discord_mautrix.existingSecret.registration) .Values.bridges.discord_mautrix.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix.discord_mautrix.registrationSecret" . }}
  labels:
  {{ include "matrix.labels" . | nindent 4}}
stringData:
  registration.yaml: |
    id: {{ .Values.bridges.discord_mautrix.config.appservice.id }}
    {{ if .Values.bridges.discord_mautrix.config.appservice.address }}
    url: {{ .Values.bridges.discord_mautrix.config.appservice.address }}
    {{- else -}}
    url: http://{{ include "matrix.fullname" .}}-bridge-discord:{{ .Values.bridges.discord_mautrix.config.appservice.port }}
    {{- end }}
    rate_limited: false
    sender_localpart: {{ .Values.bridges.discord_mautrix.registration.sender_localpart }}
    {{- if not .Values.bridges.discord_mautrix.existingSecret.registration }}
    as_token: "{{ include "matrix.discord_mautrix.as_token" . }}"
    hs_token: "{{ include "matrix.discord_mautrix.hs_token" . }}"
    {{- else }}
    as_token: "to be replace by env var in init container of pod"
    hs_token: "to be replace by env var in init container of pod"
    {{- end }}
    namespaces:
      users:
        - exclusive: true
          regex: "^@discord_.*:{{ .Values.matrix.serverName }}$"
        - exclusive: true
          regex: "^@{{ .Values.bridges.discord_mautrix.config.appservice.bot.username }}:{{ .Values.matrix.serverName }}$"
    {{- if .Values.bridges.discord_mautrix.config.bridge.encryption.allow }}
    de.sorunome.msc2409.push_ephemeral: true
    push_ephemeral: true
    {{- end }}
{{- end }}
