{{- if not .Values.bridges.discord_mautrix.existingSecret.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix.discord_mautrix.configSecret" . }}
  labels:
{{ include "matrix.labels" . | nindent 4}}
stringData:
  config.yaml: |
    {{- include "discord_config.yaml" . | indent 4 }}
{{- end }}
