apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-secret.fullname" . }}-rolebinding-cluster
  labels:
  {{- include "cluster-secret.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "cluster-secret.fullname" . }}-role-cluster'
subjects:
- kind: ServiceAccount
  name: '{{ include "cluster-secret.fullname" . }}-account'
  namespace: '{{ .Release.Namespace }}'