{{- if and .Values.coturn.enabled (not .Values.coturn.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matrix.fullname" . }}-coturn-secret
  labels:
    app.kubernetes.io/name: {{ include "matrix.name" . }}
    helm.sh/chart: {{ include "matrix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if (empty .Values.coturn.sharedSecret) }}
  # The shared secret used to compute passwords for the TURN server
  coturnSharedSecret: {{ randAlpha 24 | b64enc | quote }}
  {{ else }}
  coturnSharedSecret: {{ .Values.coturn.sharedSecret }}
  {{- end }}
{{- end }}
