{{/*
if mail.external.existingSecret is not passed in, then we create this secret to 
store the credentials without it being in a configmap in plaintext.
*/}}
{{- if and .Values.mail.enabled (not .Values.mail.external.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matrix.fullname" . }}-mail-secret
  labels:
    app.kubernetes.io/name: {{ include "matrix.name" . }}
    helm.sh/chart: {{ include "matrix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  hostname: {{ .Values.mail.external.hostname | b64enc | quote }}
  username: {{ .Values.mail.external.username | b64enc | quote }}
  password: {{ .Values.mail.external.password | b64enc | quote }}
  port: {{ .Values.mail.external.port | b64enc | quote }}
{{- end }}
