{{/*
If set, allows registration of standard or admin accounts by anyone who has the
shared secret, even if registration is otherwise disabled.
*/}}
{{- if not .Values.matrix.registration.existingSecret }}
{{- if or .Values.matrix.registration.sharedSecret .Values.matrix.registration.generateSharedSecert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matrix.fullname" . }}-registration-secret
  labels:
    app.kubernetes.io/name: {{ include "matrix.name" . }}
    helm.sh/chart: {{ include "matrix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.matrix.registration.sharedSecret }}
  registrationSharedSecret: {{ .Values.matrix.registration.sharedSecret | b64enc | quote }}
  {{ else }}
  registrationSharedSecret: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
